Job launching after 0.18 seconds in submission.
Running python job.
Changed into dir /home/masters/joe/deep-motion-analysis/gait_classification/joe_keras_work/experiments/2_LSTM
Importing 2LSTM-sm.py
Using Theano backend.
Using gpu device 0: GeForce GTX TITAN (CNMeM is disabled, cuDNN 5004)
Running 2LSTM-sm.main()
Traceback (most recent call last):
  File "/home/masters/jonathan/Spearmint/spearmint/launcher.py", line 243, in launch
    result = python_launcher(job)
  File "/home/masters/jonathan/Spearmint/spearmint/launcher.py", line 327, in python_launcher
    result = module.main(job['id'], params)
  File "/home/masters/joe/deep-motion-analysis/gait_classification/joe_keras_work/experiments/2_LSTM/2LSTM-sm.py", line 78, in main
    params = params.astype(np.float32)
AttributeError: 'dict' object has no attribute 'astype'
Problem executing the function
Job failed in 9.08 seconds.
Anything printed here will end up in the output directory for job #1
{u'drop1': array([ 0.]), u'drop2': array([ 0.]), u'lr': array([ 0.0002])}
(<type 'exceptions.AttributeError'>, AttributeError("'dict' object has no attribute 'astype'",), <traceback object at 0x7f09b6309c20>)
